# Generated by Django 4.1.7 on 2023-02-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customer_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='skillset',
        ),
        migrations.AddField(
            model_name='worker',
            name='skills',
            field=models.ManyToManyField(to='users.skill'),
        ),
    ]
